### DISCUSSION TITLE
v0.3.11

### DISCUSSION THREAD

**Discussion by ilyes319** [ACEsuit/mace#864] [Announcements]
# MACE 0.3.11 Release Notes

## Versions support updates

- Added support for new version of cuEquivariance 0.2.0 and 0.3.0 (breaking support for 0.1.0). (See https://mace-docs.readthedocs.io/en/latest/guide/cuda_acceleration.html)
- Added support for Pytorch 2.6.0.

## Enhanced Dataset Processing

- Added support for LMDB data format for efficient large dataset handling (like fairchem datasets). Supports folders of .aselmdb or .aselmdb files.  (See https://mace-docs.readthedocs.io/en/latest/guide/multipreprocessing.html#lmdb-files-preprocessing).
```yaml
# Example configuration for LMDB
train_file: "/path/data1/:/path/data2/:/path/data3/"
valid_file: "/path/valid1.lmdb:/path/valid2.lmdb"
```
- Streamlined workflow for training on multiple datasets simultaneously. Can now add lists of different datastream (ASE, lmdb and xyz). (See https://mace-docs.readthedocs.io/en/latest/guide/heterogeneous_data.html).

```yaml
# Example configuration for different datasets
heads:
  QM7:
    train_file: ["data/qm7/train.xyz", "data/qm7/train.h5", "data/qm7/database/"]
    valid_file: ["data/qm7/valid.xyz", "data/qm7_h5/valid/"]
    test_file:  ["data/qm7/test.xyz", "data/qm7/test.h5"]
```

## New Foundation Models

- **MACE-MPA-0**: Improved accuracy for materials. New default foundation model when calling `mace_mp()`.
- **MACE-OMAT-0**: New model trained on the OMAT dataset with DFT (PBE+U) VASP 54.

## Plotting training

- Add automatic plotting of training, validation and test statistics after a training run. Two arguments added to mace_run_train command line interface: 
```
--plot # activate or not the plotting, default True
--plot_frequency # If zero only at the end, else, each N epoch
```

![image](https://github.com/user-attachments/assets/dc92d945-d787-4a79-b512-981cecc432ab)

## Support for higher L and max_ell

- Switch to cuequivariance generalized CG for L, max_ell or correlation that needs to use CG that were not pre computed in e3nn 0.4.4. Now can train models with arbitrary L and max_ell.

## Installation

```bash
pip install --upgrade mace-torch

# For CUDA acceleration (CUDA 12)
pip install cuequivariance cuequivariance-torch cuequivariance-ops-torch-cu12
# For CUDA 11, use cuequivariance-ops-torch-cu11 instead
```

Please see our [documentation](https://mace-docs.readthedocs.io) for complete details on features and usage. If you encounter any issues, please report them on our [GitHub Issues page](https://github.com/ACEsuit/mace/issues).

**Full Changelog**: https://github.com/ACEsuit/mace/compare/v0.3.10...v0.3.11

<hr /><em>This discussion was created from the release <a href='https://github.com/ACEsuit/mace/releases/tag/v0.3.11'>v0.3.11</a>.</em>
