### DISCUSSION TITLE
Reducing the RMSE for my MACE models

### DISCUSSION THREAD

**Discussion by vijaymocherla** [ACEsuit/mace#898] [Q&A] [answered]
Hi, 

I am trying to train 3 different MACE models (`16e0`,`16e0+16o1`,`32e0`) for different functionals on relatively small datasets (~900-1000 configrations). For each functional, my data is split into multiple heads contributing about 250-350 configurations and there are about 37 atoms per configurations in each of the .xyz files.

For example, the config file for one of my models looks as follows:
```
# Model params
model: "ScaleShiftMACE"
num_channels: 16
max_L: 0
hidden_irreps: '16x0e'
r_max: 5.0
correlation: 2 
num_interactions: 2
forces_weight: 10
energy_weight: 1

# traning params
device: cuda
default_dtype: float64
save_cpu: yes
batch_size: 16
amsgrad: yes
max_num_epochs: 1200
swa: True
seed: 314159265
swa: yes
start_swa: 900
# swa_energy_weight: 1000
# swa_forces_weight: 1
ema: yes
ema_decay: 0.99
error_table: PerAtomRMSE

# data params
energy_key: "energy"
forces_key: "forces"
E0s: "average"
name: "pbe_16e0"
model_dir: "pbe_16e0"
log_dir: "pbe_16e0"
checkpoints_dir: "pbe_16e0"
results_dir: "pbe_16e0"

# model descriptors
heads:
  DFT:
    train_file: ["./data/train_gs_pbe_3x3x4.xyz", "./data/train_rnd_ads_pbe_3x3x4.xyz", "./data/train_thermal_slab_pbe_3x3x4.xyz"]
    valid_fraction: 0.10
    test_file: ["./data/test_gs_pbe_3x3x4.xyz", "./data/train_rnd_ads_pbe_3x3x4.xyz", ./data/test_thermal_slab_pbe_3x3x4.xyz]

```

I've tried to optimize the training of my models with different batchsizes (2,4,8,16,32). However, I am not able to improve the performance of models beyond ~1.5 RMSE E / meV/atom. Given the performance of MACE models for similar systems in [arXiv:2403.15334](https://arxiv.org/abs/2403.15334), I was expecting the error in energy to be sub meV/atom (<30 meV for a given configuration). 

**Questions**
1. Are the traning datasets too small to achieve lower RMSE for energies and forces?
2. Can I improve my traning with different configuration weights for the data from multiple heads?
3. Do I have to use larger batchsizes to improve my performance?

Here's are the final error-tables for the above model:
+-------------+---------------------+------------------+-------------------+
| config_type | RMSE E / meV / atom | RMSE F / meV / A | relative F RMSE % |
+-------------+---------------------+------------------+-------------------+
|  train_DFT  |            1.2      |         22.4     |          0.89     |
|  valid_DFT  |            1.2      |         21.5     |          0.94     |
+-------------+---------------------+------------------+-------------------+

+-------------+---------------------+------------------+-------------------+
| config_type | RMSE E / meV / atom | RMSE F / meV / A | relative F RMSE % |
+-------------+---------------------+------------------+-------------------+
| Default_DFT |            1.5      |         28.6     |          1.00     |
+-------------+---------------------+------------------+-------------------+

A plot from training the above config file looks like this: 
![pbe_16e0_run-314159265_train_DFT_stage_two](https://github.com/user-attachments/assets/f30014e4-693d-4335-b40d-e66ad56d8c8d)
